/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semesterprojekt;

import java.awt.*;
import java.awt.geom.*;
import javax.swing.*;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Adam
 */
public class SpilVindue extends javax.swing.JPanel {

    int Xpos = 0; //indeholder x for mus
    int Ypos = 0; //indeholder y for mus

    public SpilVindue() {
        initComponents();
        setBackground(Color.BLACK);
    }

    public void paintComponent(Graphics g) {

        // Herunder referer g til et Graphics-objekt man kan tegne med
        super.paintComponent(g);                // tegn først baggrunden på panelet

        g.setColor(Color.GREEN);
        g.fillRect(10, 10, 50, 50);

        g.setColor(Color.RED);
        g.fillRect(Xpos, 400, 25, 25);

        g.setColor(Color.WHITE);
        g.drawLine(Xpos, 400, 50, 50);

        g.setColor(Color.RED);
        
        g.drawString(String.valueOf(Xpos), 20, 50);

        System.out.println("Der blev tegnet!!");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        Xpos = evt.getX();
        Ypos = evt.getY();
        
        repaint();

        System.out.println("MouseMoved!");
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
